### ISSUE TITLE
Deprecation warning for Django 1.10: template.render

### ISSUE THREAD

**Issue by ivanvenosdel** [tzangms/django-bootstrap-form#77]
Catching this deprecation warning when rendering using the template tag.

```
/bootstrapform/templatetags/bootstrap.py:80: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(context)
```

**Comment by N3TC4T** [comment]
+1

**Comment by troeger** [comment]
+1

**Comment by hugoleodev** [comment]
+1

**Comment by keithyong** [comment]
+1, getting this error too.

**Comment by tzangms** [comment]
Hi all,

This issue has been fixed by @hugoleodev, and I've been merge and upload it to PyPI, it's version 3.2.1. Thanks you all guys.

**Comment by dan-klasson** [comment]
@tzangms  Seems to be a bug with this PR. The indentation here should be one more tab to the left to make it work for boundfields as well:

```
        if django_version >= (1, 8):
            context = context.flatten()
```
