### ISSUE TITLE
Alternate render path dodges Django 1.10 compatibility fix

### ISSUE THREAD

**Issue by ivanvenosdel** [tzangms/django-bootstrap-form#90]
Looks like the fix for #77 got thwarted by an indentation error.

If you take a look at this compatibility code:
https://github.com/tzangms/django-bootstrap-form/blob/master/bootstrapform/templatetags/bootstrap.py#L80

It is actually under the else when it should be covering both cases. This causes the project to be Django 1.10 incompatible under certain circumstances.

**Comment by kacchan822** [comment]
+1
