### ISSUE TITLE
Django 1.11.2: context must be a dict rather than Context.

### ISSUE THREAD

**Issue by denaje** [tzangms/django-bootstrap-form#99]
Getting this error in Django 1.11.2. It looks like the previous fix missed a use case. See https://github.com/tzangms/django-bootstrap-form/pull/82/files#r118964036 for more details.

**Comment by JoKeyser** [comment]
I guess this would be fixed as soon as PR #97 hits master?

**Comment by tzangms** [comment]
This had been fixed in this PR https://github.com/tzangms/django-bootstrap-form/pull/97
